imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:
      - SurfFrontBundle

    filters:
        less:
            node:       /usr/local/bin/node
            node_paths: ["%kernel.root_dir%/../node_modules"]
            apply_to:   "\.less$"
        cssrewrite: ~

    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/../web/components/bootstrap/less/bootstrap.less
                - %kernel.root_dir%/../web/components/bootstrap/less/responsive.less
            filters:
                - less
            output: css/bootstrap.css

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        charset:  UTF8
        path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

bc_bootstrap:
    assets_dir:  %kernel.root_dir%/../web/components/bootstrap
    jquery_path: %kernel.root_dir%/../web/components/jquery/jquery.js
